---
title: "Thomas Vroylandt"
author: Thomas Vroylandt
output:
  pagedown::html_resume:
    self_contained: false
    css: ["style/resume.css", "style/default.css"]
knit: pagedown::chrome_print
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(tidyverse)
library(glue)

# fonction de cv
print_section <- function(position_data, section_id) {
  position_data %>%
    filter(section == section_id) %>%
    arrange(desc(end)) %>%
    mutate(
      timeline = ifelse(is.na(start) | start == end,
                        end,
                        glue('{end} - {start}'))
    ) %>%
    mutate_all( ~ ifelse(is.na(.), "", .)) %>%
    glue_data(
      "### {title}",
      "\n\n",
      "{institution}",
      "\n\n",
      "{loc}",
      "\n\n",
      "{timeline}",
      "\n\n\n",
    )
}

position_data <- readxl::read_xlsx("positions_cv_en.xlsx",
                                   col_types = c("text", "logical", rep("text", 5))) %>% 
  filter(in_resume)
```

Aside
================================================================================

Infos {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-calendar"></i> Born : 1993-04-22
- <i class="fa fa-home"></i> 9-11 quai de la Canardière
- 60500 Chantilly
- FRANCE
- <i class="fa fa-phone"></i> (+33)6.47.53.39.11
- <i class="fa fa-envelope"></i> thomas@tillac-data.com
- <i class="fa fa-file-alt"></i> [www.tillac-data.com/]()
- <i class="fa fa-twitter"></i> [twitter.com/tvroylandt]()
- <i class="fa fa-github"></i> [github.com/tvroylandt]()


Skills {#competences}
--------------------------------------------------------------------------------

- R
- SAS
- SQL
- Office
- Shiny
- Git


Languages {#langues}
--------------------------------------------------------------------------------

- French
- English
- German

Main
================================================================================

Thomas Vroylandt {#title}
--------------------------------------------------------------------------------

Positions {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% 
  print_section("emploi")
```

Teaching {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
position_data %>% 
  print_section("enseignement")
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% 
  mutate(section = fct_collapse(section,
                                "formation" = c("formation_initiale", "formation_continue"))) %>% 
  print_section("formation")
```

Misc {data-icon=user-friends}
--------------------------------------------------------------------------------

```{r}
position_data %>%
  print_section("divers")
```


